export const ClientDashboards = [
  {
    cId: 1,
    pId: 1,
    showPastProjects: true,
    showProjectCompletion: true,
    // repo id should be here. For now, added project ids
    clientRepository: 1,
    projectRepository: 1,
    theme: 'dark',
    fontSize: 'medium',
  },
  {
    cId: 2,
    pId: 2,
    showPastProjects: false,
    showProjectCompletion: true,
    clientRepository: 2,
    projectRepository: 2,
    theme: 'light',
    fontSize: 'small',
  },
  {
    cId: 2,
    pId: 4,
    showPastProjects: false,
    showProjectCompletion: true,
    clientRepository: 4,
    projectRepository: 4,
    theme: 'light',
    fontSize: 'small',
  },
  {
    cId: 3,
    pId: 3,
    showPastProjects: true,
    showProjectCompletion: false,
    clientRepository: 3,
    projectRepository: 3,
    theme: 'dark',
    fontSize: 'large',
  },
  {
    cId: 4,
    pId: 4,
    showPastProjects: true,
    showProjectCompletion: true,
    clientRepository: 4,
    projectRepository: 4,
    theme: 'light',
    fontSize: 'medium',
  },
  {
    cId: 5,
    pId: 5,
    showPastProjects: false,
    showProjectCompletion: true,
    clientRepository: null,
    projectRepository: null,
    theme: 'dark',
    fontSize: 'small',
  },
  {
    cId: 6,
    pId: 6,
    showPastProjects: true,
    showProjectCompletion: false,
    clientRepository: null,
    projectRepository: null,
    theme: 'light',
    fontSize: 'large',
  },
];
