export const EmpData = [
  // empId will be given automatically from back-end
  // workedHours are current month worked hours
  {
    empId: 1,
    firstName: 'Debora',
    lastName: 'Kwon',
    role: 'developer',
    workedHours: 32,
    email: 'fake1@gmail.com',
    avatar: 'http://localhost:3000/fakeAvatars/avatar1.jpeg',
  },
  {
    empId: 2,
    firstName: 'Parshant',
    lastName: 'Rehal',
    role: 'developer',
    workedHours: 32,
    email: 'fake2@gmail.com',
    avatar: 'http://localhost:3000/fakeAvatars/avatar1.jpeg',
  },
  {
    empId: 3,
    firstName: 'Marcus',
    lastName: 'Lau',
    role: 'developer',
    workedHours: 32,
    email: 'fake3@gmail.com',
    avatar: 'http://localhost:3000/fakeAvatars/avatar1.jpeg',
  },
  {
    empId: 4,
    firstName: 'Hashem',
    lastName: 'Al-Wadeai',
    role: 'developer',
    workedHours: 32,
    email: 'fake4@gmail.com',
    avatar: 'http://localhost:3000/fakeAvatars/avatar1.jpeg',
  },
  {
    empId: 5,
    firstName: 'Ben',
    lastName: 'Wood',
    role: 'developer',
    workedHours: 32,
    email: 'fake5@gmail.com',
    avatar: 'http://localhost:3000/fakeAvatars/avatar1.jpeg',
  },
  {
    empId: 6,
    firstName: 'Reece',
    lastName: 'Cheshire',
    role: 'developer',
    workedHours: 32,
    email: 'fake6@gmail.com',
    avatar: 'http://localhost:3000/fakeAvatars/avatar1.jpeg',
  },
];
