import { projectList } from 'types/projectDetails/projectDataTypes';

export const projects: projectList = [
  {
    id: 1,
    pName: 'Project1',
    description: 'Project 1',
    estimatedHours: 60,
    currentWorkedHours: 30,
    client: 'asdf1',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 1,
        title: 'task 1',
        status: 1,
        assignedEmpIds: [1],
      },
      {
        id: 2,
        title: 'task 2',
        status: 0,
        assignedEmpIds: [2, 3],
      },
      {
        id: 3,
        title: 'task 3',
        status: -1,
        assignedEmpIds: [4],
      },
      {
        id: 4,
        title: 'task 4',
        status: -1,
        assignedEmpIds: [5, 6],
      },
      {
        id: 5,
        title: 'task 5',
        status: -1,
        assignedEmpIds: [1, 2, 3],
      },
      {
        id: 6,
        title: 'task 6',
        status: 0,
        assignedEmpIds: [4, 5, 6],
      },
    ],
  },
  {
    id: 2,
    pName: 'Project2',
    description: 'Project 2',
    estimatedHours: 80,
    currentWorkedHours: 70,
    client: 'asdf2',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 7,
        title: 'task 7',
        status: 1,
        assignedEmpIds: [2, 6],
      },
      {
        id: 8,
        title: 'task 8',
        status: 0,
        assignedEmpIds: [3, 4],
      },
      {
        id: 9,
        title: 'task 9',
        status: 0,
        assignedEmpIds: [5, 6],
      },
      {
        id: 10,
        title: 'task 10',
        status: 0,
        assignedEmpIds: [1, 2],
      },
      {
        id: 11,
        title: 'task 11',
        status: -1,
        assignedEmpIds: [2, 3, 4, 5],
      },
      {
        id: 12,
        title: 'task 12',
        status: 0,
        assignedEmpIds: [1, 2, 3, 4, 5, 6],
      },
    ],
  },
  {
    id: 3,
    pName: 'Project3',
    description: 'Project 3',
    estimatedHours: 40,
    currentWorkedHours: 0,
    client: 'asdf3',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 13,
        title: 'task 13',
        status: 1,
        assignedEmpIds: [1],
      },
      {
        id: 14,
        title: 'task 14',
        status: 1,
        assignedEmpIds: [2],
      },
      {
        id: 15,
        title: 'task 15',
        status: 1,
        assignedEmpIds: [3],
      },
      {
        id: 16,
        title: 'task 16',
        status: 1,
        assignedEmpIds: [4],
      },
      {
        id: 17,
        title: 'task 17',
        status: 1,
        assignedEmpIds: [5],
      },
      {
        id: 18,
        title: 'task 18',
        status: 1,
        assignedEmpIds: [6],
      },
    ],
  },
  {
    id: 4,
    pName: 'Project4',
    description: 'Project 4',
    estimatedHours: 250,
    currentWorkedHours: 100,
    client: 'asdf4',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 19,
        title: 'task 19',
        status: 0,
        assignedEmpIds: [2],
      },
      {
        id: 20,
        title: 'task 20',
        status: 0,
        assignedEmpIds: [],
      },
      {
        id: 21,
        title: 'task 21',
        status: 0,
        assignedEmpIds: [1],
      },
      {
        id: 22,
        title: 'task 22',
        status: 0,
        assignedEmpIds: [5],
      },
      {
        id: 23,
        title: 'task 23',
        status: 0,
        assignedEmpIds: [],
      },
      {
        id: 24,
        title: 'task 24',
        status: 0,
        assignedEmpIds: [],
      },
    ],
  },
];
