import { project } from 'views/admin/tasklists/adminDataTypes';

export const data: project = [
  {
    id: 1,
    pName: 'Project1',
    description: 'Project 1',
    estimatedHours: 60,
    currentWorkedHours: 30,
    client: 'asdf1',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 1,
        task: 'task 1',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 2,
        task: 'task 2',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 3,
        task: 'task 3',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 4,
        task: 'task 4',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 5,
        task: 'task 5',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 6,
        task: 'task 6',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 2,
    pName: 'Project2',
    description: 'Project 2',
    estimatedHours: 80,
    currentWorkedHours: 70,
    client: 'asdf2',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 7,
        task: 'task 7',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 8,
        task: 'task 8',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 9,
        task: 'task 9',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 10,
        task: 'task 10',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 11,
        task: 'task 11',
        status: -1,
        assigned: 'parshant',
      },
      {
        id: 12,
        task: 'task 12',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 3,
    pName: 'Project3',
    description: 'Project 3',
    estimatedHours: 40,
    currentWorkedHours: 0,
    client: 'asdf3',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 13,
        task: 'task 13',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 14,
        task: 'task 14',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 15,
        task: 'task 15',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 16,
        task: 'task 16',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 17,
        task: 'task 17',
        status: 1,
        assigned: 'parshant',
      },
      {
        id: 18,
        task: 'task 18',
        status: 1,
        assigned: 'parshant',
      },
    ],
  },
  {
    id: 4,
    pName: 'Project4',
    description: 'Project 4',
    estimatedHours: 250,
    currentWorkedHours: 100,
    client: 'asdf4',
    startDate: '2023-03-01',
    endDate: '2023-04-18',
    tasks: [
      {
        id: 19,
        task: 'task 19',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 20,
        task: 'task 20',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 21,
        task: 'task 21',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 22,
        task: 'task 22',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 23,
        task: 'task 23',
        status: 0,
        assigned: 'parshant',
      },
      {
        id: 24,
        task: 'task 24',
        status: 0,
        assigned: 'parshant',
      },
    ],
  },
];
