// instead of back-end now, it shows scope data in general

export const Scopes = [
  {
    date: '2023-03-20',
    status: 'rejected',
    pName: 'project1',
    clientName: 'Communica',
    scopeList: 'Request quotes',
  },
  {
    date: '2023-04-01',
    status: 'pending',
    pName: 'project1',
    clientName: 'Communica',
    scopeList: 'Help chat',
  },
  {
    date: '2023-04-02',
    status: 'pending',
    pName: 'project1',
    clientName: 'Communica',
    scopeList: 'Login page with Google sign in',
  },
  {
    date: '2023-03-12',
    status: 'approved',
    pName: 'project1',
    clientName: 'Communica',
    scopeList: 'Contact us page',
  },
  {
    date: '2023-03-15',
    status: 'approved',
    pName: 'project2',
    clientName: 'CCASA',
    scopeList: 'Login page with Google sign in',
  },
  {
    date: '2023-04-01',
    status: 'pending',
    pName: 'project2',
    clientName: 'CCASA',
    scopeList: 'Shopping cart saves items',
  },
  {
    date: '2023-03-20',
    status: 'rejected',
    pName: 'project3',
    clientName: 'ENGIN',
    scopeList: 'Help chat',
  },
  {
    date: '2023-03-22',
    status: 'approved',
    pName: 'project3',
    clientName: 'ENGIN',
    scopeList: 'Login page with Google sign in',
  },
  {
    date: '2023-04-02',
    status: 'pending',
    pName: 'project3',
    clientName: 'ENGIN',
    scopeList: 'Shopping cart saves items',
  },
  {
    date: '2023-03-28',
    status: 'rejected',
    pName: 'project4',
    clientName: 'YYC Food Fund',
    scopeList: 'Google Maps integration',
  },
  {
    date: '2023-03-28',
    status: 'approved',
    pName: 'project4',
    clientName: 'YYC Food Fund',
    scopeList: 'List of food markets',
  },
  {
    date: '2023-03-18',
    status: 'approved',
    pName: 'project4',
    clientName: 'YYC Food Fund',
    scopeList: 'Event List',
  },
  {
    date: '2023-04-01',
    status: 'pending',
    pName: 'project5',
    clientName: 'ISAIC AI',
    scopeList: 'Login page with forgot password',
  },
  {
    date: '2023-03-26',
    status: 'approved',
    pName: 'project5',
    clientName: 'ISAIC AI',
    scopeList: 'View of AI business',
  },
  {
    date: '2023-03-28',
    status: 'rejected',
    pName: 'project5',
    clientName: 'ISAIC AI',
    scopeList: 'AI chat',
  },
];
